// SPI0_TX 19
// SPI0_SCK 18
// SPI0_CSn 17

#include <stdio.h>
#include <string.h>
#include <math.h>
#include "pico/stdlib.h"
#include "pico/binary_info.h"
#include "hardware/spi.h"


#ifdef PICO_DEFAULT_SPI_CSN_PIN
static inline void cs_select() {
    asm volatile("nop \n nop \n nop");
    gpio_put(PICO_DEFAULT_SPI_CSN_PIN, 0);  // Active low
    asm volatile("nop \n nop \n nop");
}

static inline void cs_deselect() {
    asm volatile("nop \n nop \n nop");
    gpio_put(PICO_DEFAULT_SPI_CSN_PIN, 1);
    asm volatile("nop \n nop \n nop");
}
#endif

static void sendSPI(unsigned int adcCounts, unsigned int channel) {
    uint8_t buf[2];

    uint8_t adcCounts4MostSignificant = (adcCounts >> 6);
    uint8_t adcCounts6LeastSignificant = (adcCounts & 0b0000111111);

    buf[0] = channel << 7; // encapsulate channel info. 0=A, 1=B
    buf[0] |= 0b01110000; // encapsulate 111 for buffer on, 1x gain, and active mode.
    buf[0] |= adcCounts4MostSignificant; // encapsulate 4 most significant

    buf[1] = (adcCounts6LeastSignificant << 2); // encapsulate 6 least significant
    
    cs_select();
    spi_write_blocking(spi_default, buf, 2); // write the two 8-bit arrays in succession.
    cs_deselect();
}

int main() {
  stdio_init_all();
  
  // spi init
  spi_init(spi_default, 500 * 1000); // Hz
  gpio_set_function(PICO_DEFAULT_SPI_RX_PIN, GPIO_FUNC_SPI);
  gpio_set_function(PICO_DEFAULT_SPI_SCK_PIN, GPIO_FUNC_SPI);
  gpio_set_function(PICO_DEFAULT_SPI_TX_PIN, GPIO_FUNC_SPI);

  // Chip select is active-low, so initialize to high
  gpio_init(PICO_DEFAULT_SPI_CSN_PIN);
  gpio_set_dir(PICO_DEFAULT_SPI_CSN_PIN, GPIO_OUT);
  gpio_put(PICO_DEFAULT_SPI_CSN_PIN, 1);


  // the following code to generate the waves are generated by AI.
  unsigned int sinWave[100];
  unsigned int triangleWave[100];
  for (int i = 0; i < 100; i++) {
    // Generate 2Hz sine wave
    float sineValue = sin(2 * 3.14 * i / 50);
    sinWave[i] = (unsigned int) ((sineValue + 1) / 2 * 1023); // Scale and shift sine value to 0-1023 range
  }

  const unsigned int maxVal = 1023;
  const int halfCycle = 50; // Half of the samples for a complete cycle

  for (int i = 0; i < 100; i++) {
      if (i < halfCycle) {
          // First half: Linearly increase from 0 to 1023
          triangleWave[i] = (unsigned int)(((double)i / (halfCycle - 1)) * maxVal);
      } else {
          // Second half: Linearly decrease from 1023 to 0
          triangleWave[i] = (unsigned int)(((double)(100 - i - 1) / (halfCycle - 1)) * maxVal);
      }
  }

  while (1) {

    for (unsigned int i = 0; i < 100; i++) {
      sendSPI(sinWave[i], 0);
      sleep_ms(5);
      sendSPI(triangleWave[i], 1);
      sleep_ms(5);
    }

  }

  return 0;
  }